spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/reservaciones
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true

